/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.countriesdbmanager;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author suleymanov
 */
public class frmMainDatabaseManager extends javax.swing.JFrame {

	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMainDatabaseManager.class.getName());

	/**
	 * Creates new form frmMainDatabaseManager
	 */
	DefaultTableModel model = new DefaultTableModel();

	public frmMainDatabaseManager() {
		initComponents();
		refreshTableCountries();
	}
	public  void refreshTableCountries(){
		model = (DefaultTableModel) tblCountries.getModel();
		model.setRowCount(0);
		ArrayList<Country> countries = getCountry();
		
		for (Country country : countries) {
			Object[] row = {country.getCountry_id(), country.getName(), country.getContinent(), country.getRegion(), country.getPopulation(), country.getCapital()};
			model.addRow(row);
		}
	}

	public ArrayList<Country> getCountry() {
		DbHelper helper = new DbHelper();
		ResultSet resultSet;
		ArrayList<Country> countries = null;

		try (Connection connection = helper.getConnection()) {
			Statement statment = null;
			statment = connection.createStatement();
			resultSet = statment.executeQuery("SELECT * FROM countries");
			countries = new ArrayList<>();
			while (resultSet.next()) {
				countries.add(new Country(
					resultSet.getInt("country_id"),
					resultSet.getString("name"),
					resultSet.getString("continent"),
					resultSet.getString("region"),
					resultSet.getInt("population"),
					resultSet.getString("capital")
				));
			}
		} catch (SQLException exception) {
			helper.showErrorMessage(exception);
		}
		return countries;
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                tblCountries = new javax.swing.JTable();
                lblSearch = new javax.swing.JLabel();
                tbxSearch = new javax.swing.JTextField();
                lblName = new javax.swing.JLabel();
                txbName = new javax.swing.JTextField();
                txbContinent = new javax.swing.JTextField();
                lblContinent = new javax.swing.JLabel();
                txbRegion = new javax.swing.JTextField();
                txbPopulation = new javax.swing.JTextField();
                lblPopulation = new javax.swing.JLabel();
                lblRegion = new javax.swing.JLabel();
                txbCapital = new javax.swing.JTextField();
                lblCapital = new javax.swing.JLabel();
                btnAdd = new javax.swing.JToggleButton();
                btnRfresh = new javax.swing.JToggleButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                tblCountries.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                tblCountries.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Country_id", "Name", "Continent", "Region", "Population", "Capital"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false, false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane1.setViewportView(tblCountries);

                lblSearch.setBackground(new java.awt.Color(51, 51, 51));
                lblSearch.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                lblSearch.setText("Search:");
                lblSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                tbxSearch.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tbxSearchKeyReleased(evt);
                        }
                });

                lblName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                lblName.setText("Name: ");

                txbName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txbNameActionPerformed(evt);
                        }
                });

                txbContinent.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txbContinentActionPerformed(evt);
                        }
                });

                lblContinent.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                lblContinent.setText("Continent:");

                txbRegion.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txbRegionActionPerformed(evt);
                        }
                });

                txbPopulation.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txbPopulationActionPerformed(evt);
                        }
                });

                lblPopulation.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                lblPopulation.setText("Population:");

                lblRegion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                lblRegion.setText("Region:");

                txbCapital.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txbCapitalActionPerformed(evt);
                        }
                });

                lblCapital.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                lblCapital.setText("Capital: ");

                btnAdd.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                btnAdd.setText("add");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });

                btnRfresh.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                btnRfresh.setText("refresh");
                btnRfresh.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRfreshActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblSearch)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnRfresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txbName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblContinent, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txbContinent, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txbPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txbCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(40, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRfresh))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblContinent, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txbContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txbPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txbCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAdd))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(16, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void tbxSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxSearchKeyReleased
		String searchKey = tbxSearch.getText();
		TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<>(model);
		tblCountries.setRowSorter(tableRowSorter);
		tableRowSorter.setRowFilter(RowFilter.regexFilter(searchKey));
        }//GEN-LAST:event_tbxSearchKeyReleased

        private void txbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbNameActionPerformed

        }//GEN-LAST:event_txbNameActionPerformed

        private void txbContinentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbContinentActionPerformed

        }//GEN-LAST:event_txbContinentActionPerformed

        private void txbRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbRegionActionPerformed

        }//GEN-LAST:event_txbRegionActionPerformed

        private void txbPopulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbPopulationActionPerformed

        }//GEN-LAST:event_txbPopulationActionPerformed

        private void txbCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbCapitalActionPerformed

        }//GEN-LAST:event_txbCapitalActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
		DbHelper helper = new DbHelper();
		PreparedStatement preparedStatement = null;
		Connection connection = null;

		try {
			String sql = "INSERT INTO countries (name, continent, region, population, capital) VALUES (?, ?, ?, ?, ?) ";
			connection = helper.getConnection();
			preparedStatement = connection.prepareStatement(sql);
			preparedStatement.setString(1, txbName.getText());
			preparedStatement.setString(2, txbContinent.getText());
			preparedStatement.setString(3, txbRegion.getText());
			preparedStatement.setInt(4, Integer.parseInt(txbPopulation.getText()));
			preparedStatement.setString(5, txbCapital.getText());
			preparedStatement.executeUpdate();
			refreshTableCountries();
		} catch (SQLException exception) {
			helper.showErrorMessage(exception);
		} finally {
			 try {
				if (preparedStatement != null) preparedStatement.close();
				if (connection != null) connection.close();
			 } catch (SQLException e) {
				 helper.showErrorMessage(e);
			}
		}
        }//GEN-LAST:event_btnAddActionPerformed

        private void btnRfreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRfreshActionPerformed
	refreshTableCountries();
        }//GEN-LAST:event_btnRfreshActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new frmMainDatabaseManager().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JToggleButton btnAdd;
        private javax.swing.JToggleButton btnRfresh;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblCapital;
        private javax.swing.JLabel lblContinent;
        private javax.swing.JLabel lblName;
        private javax.swing.JLabel lblPopulation;
        private javax.swing.JLabel lblRegion;
        private javax.swing.JLabel lblSearch;
        private javax.swing.JTable tblCountries;
        private javax.swing.JTextField tbxSearch;
        private javax.swing.JTextField txbCapital;
        private javax.swing.JTextField txbContinent;
        private javax.swing.JTextField txbName;
        private javax.swing.JTextField txbPopulation;
        private javax.swing.JTextField txbRegion;
        // End of variables declaration//GEN-END:variables
}
